### ISSUE TITLE
Creating my own inputs

### ISSUE THREAD

**Issue by zhangj150** [clab/rnng#3]
Dear @adhigunasurya ,
I have been trying to create my own input using [Stanford parser](http://nlp.stanford.edu:8080/parser/) on texts and then cleaning the results to match the sample input format.  However, after running the commands to train the discriminative model

```{r, engine='bash', count_lines}
python get_oracle.py cleanedTraining.txt cleanedTraining.txt > train.oracle
python get_oracle.py cleanedTraining.txt cleanedDevSet.txt > dev.oracle
python get_oracle.py cleanedTraining.txt sample_input_english.txt > test.oracle
nohup build/nt-parser/nt-parser --cnn-mem 1700 -x -T train.oracle -d dev.oracle -C cleanedDevSet.txt -P -t --lstm_input_dim 128 --hidden_dim 128 -D 0.2 > log.txt
```
I get "Correct action list exhausted, but not in final parser state" in log.txt
what does this mean? 
([cleanedTraining.txt](https://github.com/clab/rnng/files/709907/cleanedTraining.txt))
([cleanedDevSet.txt](https://github.com/clab/rnng/files/709943/cleanedDevSet.txt))

**Comment by adhigunasurya** [comment]
Hi Jonathan,

The issue is that in the file that you attached, all the trees (for many different sentences) are in the same line. Make sure that the format is one tree/sentence, and one tree per line.

I've attached an example of this by modifying the "cleanedTraining.txt" that you attached. I checked with the new file and it seems to work.

Let us know if any further issues.

[cleanedTraining_modified.txt](https://github.com/clab/rnng/files/730271/cleanedTraining_modified.txt)
