### ISSUE TITLE
How did you get 49 unk types?

### ISSUE THREAD

**Issue by helson73** [clab/rnng#4]
I use your script to preprocess PTB train(2-21) data, found 66 unk types.
But in your paper, it reported 49.
Did you revised your code after publication ?

**Comment by adhigunasurya** [comment]
Yes we made some modifications to the code after the initial paper some published (the current code to get the oracle is in Python, while the original one was in Perl). There are some minor differences due to the implementation details (based on the Berkeley parser UNKification code), but I just checked again and you are right and I also get 66 UNK types. To my best knowledge, this should not affect performance, kindly let me know if you encounter a big gap in performance than the reported results.
